### ISSUE TITLE
MariaDB upgrade script for 12.x fails with "Data too long for column 'if_condition'"

### ISSUE THREAD

**Issue by slaudel** [opencast/opencast#4226]
**Describe the bug**
When running the python update script "_workflows_mariadb.py_" for converting database from opencast 11 to 12 I encounter the following error:

```
Migrating workflow 59187586 (14837/14849)
Migrating workflow 59187818 (14838/14849)
Migrating workflow 59187821 (14839/14849)
Traceback (most recent call last):
File "workflows_mariadb.py", line 368, in <module>
insert_parsed(create_workflow_operation_sql, workflow_operations)
File "workflows_mariadb.py", line 67, in insert_parsed
cursor.executemany(sql, data)
File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 674, in executemany
return self.execute(stmt)
File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 572, in execute
self._handle_result(self._connection.cmd_query(stmt))
File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 922, in cmd_query
result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 732, in _handle_result
raise errors.get_exception(packet)
mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'if_condition' at row 16
```

After dropping this workflow number 59187821 from "oc_jobs" table the migration runs without an issue.

**Environment Information**
 - OS: Alma Linux 8.6
 - Opencast 12.2.0 - a4c7257 - from RPM Repo
 - Python 3.6.8
 - MariaDB Server version: 10.3.32-MariaDB-log
 - mysql_connector_python==8.0.29
 - update script downloaded directly from github

**Comment by mtneug** [comment]
Fixed by #4221

**Comment by slaudel** [comment]
I've tried this fix but it does not seem to fix. Now the problem arises earlier:

> Creating connection to database...
> Connection to database successful
> Create tables...
> Query executed successfully
> Query executed successfully
> Traceback (most recent call last):
>   File "workflows_mariadb.py", line 201, in <module>
>     execute_query(connection, create_workflow_operation_table)
>   File "workflows_mariadb.py", line 52, in execute_query
>     cursor.execute(query)
>   File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 572, in execute
>     self._handle_result(self._connection.cmd_query(stmt))
>   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 922, in cmd_query
>     result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
>   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 732, in _handle_result
>     raise errors.get_exception(packet)
> mysql.connector.errors.ProgrammingError: 1074 (42000): Column length too big for column 'if_condition' (max = 16383); use BLOB or TEXT instead
