### ISSUE TITLE
ffmpeg 6.1 - Cutting the recording according to the edit decision list fails

### ISSUE THREAD

**Issue by marcusm7** [opencast/opencast#5595]
**Describe the bug**
Workflow step "Cutting the recording according to the edit decision list" in workflow "Publish" fails for certain videos.
The bug occurs since the update of ffmpeg on the worker nodes.
```
old:
ffmpeg version N-109363-g6c814093d8 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r4) 20220924

new:
ffmpeg version 6.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
```
The workflow operation runs for a while and fails with "Ffmpeg exited abnormally with status 137" (which means the oomkiller appeared to fetch its soul).

I was *not* able to reproduce the error with https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz or the above mentioned N-109363-g6c814093d8 or ffmpeg 4.4.

**To Reproduce**

1. Make sample video or download [here](https://cloud.uni-konstanz.de/index.php/s/jPsfoLfk67LGFHG) (if input.mp4 is not there yet, I'm still uploading)  or create your own:
Invoke and wait
```
#!/bin/bash
duration=5295.38
ffmpeg \
 -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/random \
 -ar 48000 -ac 2 -f s16le -i /dev/random -c:a aac -c:v libx264 -preset superfast -crf 20 -maxrate 8M -bufsize 16M \
 -t "$duration" \
 input.mp4
```
There is a real world lecture recording, but I didn't want to make it publicly available. So please use this war of the ants video instead.

2. Invoke ffmpeg and wait (ffmpeg version 6.1-static https://johnvansickle.com/ffmpeg/):
The ffmpeg parameters come from the opencast.log, I just added some line feeds and hyphens.
```
ffmpeg \
 -y \
 -i input.mp4 \
  -filter_complex "[0:v]trim=190.73:duration=2807.62","scale=w=trunc(in_w/2)*2:h=trunc(in_h/2)*2","setpts=PTS-STARTPTS","fade=t=in:st=0:d=0.2","fade=t=out:st=2807.42:d=0.2[v0];[0:a]atrim=190.73:duration=2807.62","asetpts=PTS-STARTPTS","afade=t=in:st=0:d=0.2","afade=t=out:st=2807.42:d=0.2[a0];[0:v]trim=3276.95:duration=1996.39","scale=w=trunc(in_w/2)*2:h=trunc(in_h/2)*2","setpts=PTS-STARTPTS","fade=t=in:st=0:d=0.2","fade=t=out:st=1996.19:d=0.2[v1];[0:a]atrim=3276.95:duration=1996.39","asetpts=PTS-STARTPTS","afade=t=in:st=0:d=0.2","afade=t=out:st=1996.19:d=0.2[a1];[v0][v1]concat=n=2:unsafe=1[ov0];[a0][a1]concat=n=2:v=0:a=1[oa0]" \
 -preset veryfast \
 -crf 18 \
 -tune film \
 -map_metadata -1 \
 -map_chapters -1 \
 -sn \
 -dn \
 -map [oa0] \
 -map [ov0] \
 -c:v libx264 \
 -c:a aac \
 output.mp4
```
3. ffmpeg starts to eat up all the memory (real and virtual):
![worker1 ohnomorememory](https://github.com/opencast/opencast/assets/77965251/28c75aca-4264-4756-846d-8c27909e23da)

4. The worker node runs out of memory and the Oomkiller appears to remove the process. Syslog:
```
Feb 06 11:24:52 oc-worker-01 kernel: Connector-Sched invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
...
Feb 06 11:24:52 oc-worker-01 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/open>
Feb 06 11:24:52 oc-worker-01 kernel: Out of memory: Killed process 169300 (ffmpeg) total-vm:26292404kB, anon-rss:15553264kB, file-rss:0kB, shmem-rss:0kB,>
Feb 06 11:24:54 oc-worker-01 kernel: oom_reaper: reaped process 169300 (ffmpeg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
5. The opencast.log states:
```
2024-02-06T11:24:54,496 | ERROR | (FFmpegEdit:137) - VideoEditor ffmpeg failed
java.lang.Exception: Ffmpeg exited abnormally with status 137
```
6. The UI shows *failed* at the  "Cutting the recording according to the edit decision list" in workflow "Publish".

**Expected behavior**
The workflow step finishes as intended with status "Succeeded".

**Stack trace**

opencast.log
```
2024-02-06T11:00:45,972 | INFO  | (FFmpegEdit:115) - executing command: /usr/bin/ffmpeg -y -i /srv/oc-storage/workspace/https_admin.opencast.uni-konstanz.
de/assets/assets/c1a5ec63-70f3-4cc5-89b6-4868e6ba5061/514eed5f-6c81-4690-9dd7-a68fd5f15fba/5/514eed5f-6c81-4690-9dd7-a68fd5f15fba.mp4 -filter_complex [0:v
]trim=190.73:duration=2807.62,scale=w=trunc(in_w/2)*2:h=trunc(in_h/2)*2,setpts=PTS-STARTPTS,fade=t=in:st=0:d=0.2,fade=t=out:st=2807.42:d=0.2[v0];[0:a]atri
m=190.73:duration=2807.62,asetpts=PTS-STARTPTS,afade=t=in:st=0:d=0.2,afade=t=out:st=2807.42:d=0.2[a0];[0:v]trim=3276.95:duration=1996.39,scale=w=trunc(in_
w/2)*2:h=trunc(in_h/2)*2,setpts=PTS-STARTPTS,fade=t=in:st=0:d=0.2,fade=t=out:st=1996.19:d=0.2[v1];[0:a]atrim=3276.95:duration=1996.39,asetpts=PTS-STARTPTS
,afade=t=in:st=0:d=0.2,afade=t=out:st=1996.19:d=0.2[a1];[v0][v1]concat=n=2:unsafe=1[ov0];[a0][a1]concat=n=2:v=0:a=1[oa0] -preset veryfast -crf 18 -tune fi
lm -map_metadata -1 -map_chapters -1 -sn -dn -map [oa0] -map [ov0] -c:v libx264 -c:a aac /srv/oc-storage/workspace/editor/1709795/presenter/work-514eed5f-
6c81-4690-9dd7-a68fd5f15fba.mp4

...

2024-02-06T11:24:54,496 | ERROR | (FFmpegEdit:137) - VideoEditor ffmpeg failed
java.lang.Exception: Ffmpeg exited abnormally with status 137
        at org.opencastproject.videoeditor.ffmpeg.FFmpegEdit.run(FFmpegEdit.java:133) ~[?:?]
        at org.opencastproject.videoeditor.ffmpeg.FFmpegEdit.processEdits(FFmpegEdit.java:104) ~[?:?]
        at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.processSmil(VideoEditorServiceImpl.java:322) ~[?:?]
        at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.process(VideoEditorServiceImpl.java:514) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
2024-02-06T11:24:55,980 | INFO  | (ServiceRegistryJpaImpl:1327) - Unregistering Service org.opencastproject.videoeditor@https://oc-worker-01.kim.uni-konst
anz.de and cleaning its running jobs
2024-02-06T11:24:56,094 | INFO  | (ServiceRegistryJpaImpl:1327) - Unregistering Service org.opencastproject.ingestdownload@https://oc-worker-01.kim.uni-ko
nstanz.de and cleaning its running jobs
2024-02-06T11:24:56,116 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'PROCESS_SMIL':
org.opencastproject.videoeditor.api.ProcessFailedException: Unable to process SMIL: Editing pipeline exited abnormally! Error: java.lang.Exception: Ffmpeg exited abnormally with status 137
        at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.processSmil(VideoEditorServiceImpl.java:418) ~[?:?]
        at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.process(VideoEditorServiceImpl.java:514) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.opencastproject.videoeditor.api.ProcessFailedException: Editing pipeline exited abnormally! Error: java.lang.Exception: Ffmpeg exited abnormally with status 137
        at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.processSmil(VideoEditorServiceImpl.java:327) ~[?:?]
        ... 7 more
```

syslog:
```
Feb 06 11:24:52 oc-worker-01 kernel: Connector-Sched invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
...
Feb 06 11:24:52 oc-worker-01 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/open>
Feb 06 11:24:52 oc-worker-01 kernel: Out of memory: Killed process 169300 (ffmpeg) total-vm:26292404kB, anon-rss:15553264kB, file-rss:0kB, shmem-rss:0kB,>
Feb 06 11:24:54 oc-worker-01 kernel: oom_reaper: reaped process 169300 (ffmpeg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Server environment:**
 - OS: Ubuntu 22.04.3 LTS
 - Distribution: admin+presentation+worker
- Installation method: ansible-playbook
- Version opencast-14-admin,opencast-14-worker 14.4-1 from https://pkg.opencast.org/debian 14.x/stable amd64 

**Additional context**

The error can be observed on a machine with 16GiB RAM + 10GiB swap and also on a machine with 64GiB RAM + 64GiB swap. Additional files can be found [here](https://cloud.uni-konstanz.de/index.php/s/jPsfoLfk67LGFHG).

**Comment by pselsa** [comment]
With OC 15.1 I am getting oom with both `ffmpeg version N-109363-g6c814093d8` and `ffmpeg 6.1-static`

**Comment by mwuttke** [comment]
We have also been able to detect the error in our OC system with large videos (Videos  90min / 2 GB (Cam) + 200 MB (Slides) / MP4).

**Server environment:**
    OS: Debian 12 (bookworm)
    Distribution: adminpresentation +3x worker
    Installation method: ansible-playbook
    Version opencast-14-adminpresentation,opencast-14-worker 14.4-1 from https://pkg.opencast.org/debian 14.x/stable amd64

We then switched back to the old version of ffmpeg. Now this error does not occur:

```
apt policy ffmpeg-dist
ffmpeg-dist:
  Installed: 6.0-1
  Candidate: 6.1-1
  Version table:
     6.1-1 500
        500 https://pkg.opencast.org/debian 14.x/stable amd64 Packages
 *** 6.0-1 500
        500 https://pkg.opencast.org/debian 14.x/stable amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by pselsa** [comment]
Allright, i testet OC 15.1 with ffmpeg 6.1, 6.0, 4.4.2, N-109363-g6c814093d8 and  N-68533-gcc774cd962 (the one from https://johnvansickle.com/ ) - none of them is working. My test video file is quite small (9mb) and we definitely have enough ram on the worker (4gb) - I would now rather suspect OC 15.1 itself to be the problem since with 15.0 everything worked fine in the same setup and the same ffmpeg version

**Comment by pselsa** [comment]
This is by the way the ffmpeg command from opencast.log:
```
/opt/ffmpeg-git-20240203-amd64-static/ffmpeg \
-nostdin \
-nostats \
-i \
test.mp4 \
-filter:v \
scale=854:854:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
-pix_fmt \
yuv420p \
-c:v \
libx264 \
-profile:v \
high \
-level \
4.0 \
-crf \
23 \
-x264opts \
keyint=25:min-keyint=25:no-scenecut \
-maxrate \
800k \
-bufsize \
1600k \
-c:a \
aac \
-b:a \
64k \
-ac \
2 \
-movflags \
faststart \
480p.mp4 \
-filter:v \
scale=1280:1280:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
-pix_fmt \
yuv420p \
-c:v \
libx264 \
-profile:v \
high \
-level \
4.0 \
-crf \
23 \
-x264opts \
keyint=25:min-keyint=25:no-scenecut \
-maxrate \
1200k \
-bufsize \
2400k \
-c:a \
aac \
-b:a \
96k \
-ac \
2 \
-movflags \
faststart \
720p.mp4 \
-filter:v \
scale=1920:1920:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
-pix_fmt \
yuv420p \
-c:v \
libx264 \
-profile:v \
high \
-level \
4.0 \
-crf \
23 \
-x264opts \
keyint=25:min-keyint=25:no-scenecut \
-maxrate \
4000k \
-bufsize \
8000k \
-c:a \
aac \
-b:a \
96k \
-ac \
2 \
-movflags \
faststart \
1080p.mp4 \
-filter:v \
scale=2560:2560:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
-pix_fmt \
yuv420p \
-c:v \
libx264 \
-profile:v \
high \
-level \
5.0 \
-crf \
23 \
-x264opts \
keyint=25:min-keyint=25:no-scenecut \
-maxrate \
9800k \
-bufsize \
19600k \
-c:a \
aac \
-b:a \
96k \
-ac \
2 \
-movflags \
faststart \
1440p.mp4 \
-filter:v \
scale=3840:3840:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
-pix_fmt \
yuv420p \
-c:v \
libx264 \
-profile:v \
high \
-level \
5.1 \
-crf \
23 \
-x264opts \
keyint=25:min-keyint=25:no-scenecut \
-maxrate \
14800k \
-bufsize \
29600k \
-c:a \
aac \
-b:a \
96k \
-ac \
2 \
-movflags \
faststart \
2160p.mp4
```

**Comment by mtneug** [comment]
@schuettloeffel-elsa, can you retry with the latest master build from JVS (currently `20240213` with version tag `N-68649-g40c5c19eac-static`)? I cannot reproduce the memory leak with this version. Hopefully, this was fixed. I have only looked briefly at the changes between `cc774cd962` and `40c5c19eac` but haven't found a commit that stood out immediately.

**Comment by pselsa** [comment]
I am sorry, still the same problem. Just to be clear: I only installed the different ffmpeg version on the one worker node we use, not on the admin node. I assume that this souldnt affect the outcome

**Comment by mtneug** [comment]
ok so I tested the following version directly using the FFmpeg command below. In summary:

| version | url |
|---|---|
| `eeb280f351` (last Opencast build) | https://radosgw.public.os.wwu.de/opencast-ffmpeg-static/ffmpeg-20221226041111-N-109457-geeb280f351.tar.xz |
| 5.1.1 (JVS) | https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-5.1.1-amd64-static.tar.xz |
| 6.0 (JVS) | https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-6.0-amd64-static.tar.xz |
| 6.0.1 (JVS) | https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-6.0.1-amd64-static.tar.xz |
| 6.1 (JVS) | https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz |
| `cc774cd962` (JVS) | |
| `40c5c19eac` (JVS) | https://www.johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz |

I used the following test command:

```sh
$ ffmpeg \
    -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom \
    -filter_complex "
      [0:v] trim=5:duration=5 [v0];
      [0:v] trim=50:duration=5 [v1];
      [v0][v1] concat=n=2:unsafe=1 [ov0]
    " \
    -map [ov0] \
    -f null -
```

To measure the memory usage, I used `valgrind`:

```sh
$ valgrind --tool=massif --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out ffmpeg ...
```

In summary, the following memory usage can be observed:

| version | memory | max total bytes |
|---|---|---:|
| `eeb280f351` (last Opencast build) | ok | (~ 86,84 MB) `91,062,272` |
| 5.1.1 (JVS) | ok | (~ 222,14 MB) `232,935,424` |
| 6.0 (JVS) | ok | (~ 413,16 MB) `433,233,920` |
| 6.0.1 (JVS) | ok | (~ 428,13 MB) `448,925,696` |
| 6.1 (JVS) | increases | (~ 4,49 GB) `4,820,471,808` |
| `cc774cd962` (JVS) | ok | (~ 644,63 MB) `675,942,400` |
| `40c5c19eac` (JVS) | ok | (~ 644,66 MB) `675,979,264` |

So newer versions allocate more memory, and 6.1 has some kind of memory leak having to do with (omitted frames from) the filter graph. Current FFmpeg master seems to be fine. So next release of FFmpeg is likely fine. However, you have to expect more memory to be used.

You can see the shortened output including the graph of `ms_print massif.out` below.

---

<details>
<summary>eeb280f351</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
86.84^        #
     |        #@@@::::::::::::@@:::::::::@::::::::::::::::@::::::::::::::::@::
     | :::::@@#@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
     | : :::@ #@@ : : :: :: : @ :: : ::::@: :: : ::::::: :@:: : ::::::: :::@::
   0 +----------------------------------------------------------------------->s
     0                                                                   12.83

...
```

</details>

<details>
<summary>5.1.1</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
222.1^        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
     | @:@::::@                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     | @ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
     |@@ @:   @                                                              #
   0 +----------------------------------------------------------------------->s
     0                                                                   11.62

...
```

</details>

<details>
<summary>6.0</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
413.2^        #
     |        #
     |        #
     |        #
     |        #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     |        #:                                                             :
     |        #:                                                             @
     | @::::::#:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     | @      #:                                                             @
     |@@      #:                                                             @
     |@@      #:                                                             @
     |@@      #:                                                             @
     |@@      #:                                                             @
   0 +----------------------------------------------------------------------->s
     0                                                                   12.04

...
```

</details>

<details>
<summary>6.0.1</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
428.1^         #
     |         #
     |         #
     |         #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     |         #:                                                            :
     |         #:                                                            :
     | @       #:                                                            @
     | @:::::::#:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     | @       #:                                                            @
     |@@       #:                                                            @
     |@@       #:                                                            @
     |@@       #:                                                            @
     |@@       #:                                                            @
   0 +----------------------------------------------------------------------->s
     0                                                                   12.79

...
```

</details>

<details>
<summary>6.1</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    GB
4.489^                                                                      #
     |                                                                    @:#:
     |                                                                @:@:@:#:
     |                                                            @:@:@:@:@:#:
     |                                                         @:@@:@:@:@:@:#:
     |                                                       @:@:@@:@:@:@:@:#:
     |                                                   @:@:@:@:@@:@:@:@:@:#:
     |                                               ::@:@:@:@:@:@@:@:@:@:@:#:
     |                                            :::::@:@:@:@:@:@@:@:@:@:@:#:
     |                                        :::::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                                      :::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                                   ::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                               ::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                           ::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                         ::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                     ::::::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |                  :::::::::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |              :::::::::::::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     |            :::::::::::::::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
     | ::::::::::::::::::::::::::::::::::::::::: ::::::@:@:@:@:@:@@:@:@:@:@:#:
   0 +----------------------------------------------------------------------->s
     0                                                                   14.64

...
```

</details>

<details>
<summary>cc774cd962</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg-cc -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
644.6^       #
     |       #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     |       #                                                               :
     |       #                                                               :
     | @@    #                                                               @
     | @@::::#                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     | @@    #                                                               @
     |@@@    #                                                               @
     |@@@    #                                                               @
     |@@@    #                                                               @
   0 +----------------------------------------------------------------------->s
     0                                                                   13.05

...
```

</details>

<details>
<summary>40c5c19eac</summary>

```
--------------------------------------------------------------------------------
Command:            ./ffmpeg -f rawvideo -video_size 1920x1080 -pixel_format yuvj420p -framerate 30 -i /dev/urandom -filter_complex [0:v] trim=5:duration=5 [v0];[0:v] trim=50:duration=5 [v1];[v0][v1] concat=n=2:unsafe=1 [ov0] -map [ov0] -f null -
Massif arguments:   --pages-as-heap=yes --time-unit=ms --massif-out-file=massif.out
ms_print arguments: /data/massif.out
--------------------------------------------------------------------------------


    MB
644.7^        #
     |        #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     |        #                                                              :
     |        #                                                              :
     | :@    :#                                                              @
     | :@:::::#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     | @@    :#                                                              @
     |@@@    :#                                                              @
     |@@@    :#                                                              @
     |@@@    :#                                                              @
   0 +----------------------------------------------------------------------->s
     0                                                                   12.77

...
```

</details>

**Comment by mtneug** [comment]
@gregorydlogan, @lkiesow: so FFmpeg 6.1 has a memory problem which seems to be fixed in current master. However, newer versions and current master still allocate more than older versions. Question is what to package. I would suggest to pick a current JVS master build and package that with current Opencast versions. Once FFmpeg 6.2 / 7.0 is out, we can test again. What do you think?

**Comment by mtneug** [comment]
We will package `40c5c19eac` for Opencast 14 / 15. I already updated the container images for versions 15.2 and 14.9.

**Comment by kruemelm0nsta** [comment]
On OC 14.4 ffmpeg version N-68649-g40c5c19eac-static tested on one worker node solves the memory issue. Tested with videos that failed before (about 90min video 5.7GB + slides 1.4GB)

**Comment by mtneug** [comment]
@kruemelm0nsta thanks for the feedback. I will close this. DEBs and container images already ship the new version. Not sure about RPMs, but if not this will soon be the case.

**Comment by DZenker** [comment]
I'm just realizing the same issue after updating from Opencast 14.x to current 15.9 version which also updated FFMpeg to version 6.1. I'm using the Opencast RPM repo for RHEL8/9. 
So I have the assumption that the fixed FFmpeg version mentioned above is not yet included in the RPMs, right?

**Comment by gregorydlogan** [comment]
Ping @lkiesow since he'd know best.  Looking at the S3 bucket, ffmpeg-7.0.1-1 is in the OC 16 release repo, but I don't see anything newer than 6.1 in OC 15 at all.
